### ISSUE TITLE
Persistent Nav Scrolling Issues

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSU-spine#235]
Some model and OS combinations still failing to scroll in mobile view. When menu is longer than screen, menu is frozen and content scrolls instead of Spine. Confirmed on:

Samsung S4 (SCH-1545) using Android Version 4.4.2. Observed here: http://creamery.wsu.edu/ferdinands-ice-cream-shoppe/hours-and-location/
There is a Google map embedded on the page, which may be interfering with the scroll event.

**Comment by jbickelhaupt** [comment]
Add pages within http://education.wsu.edu to the list of examples. Witnessed it on pages that didn't even have a Google map in the content. Their current site is using the UP CMS in case that helps narrow things even further for you.

**Comment by laffky** [comment]
While getting some new websites setup for Global Campus we noticed this issue (http://connections.wsu.edu/ ) so I took a look at a couple other websites to see if the issue was only with our sites and something we were doing or if this was a bug. We noticed this issues where the content scrolls instead of the navigation on the following sites.

http://brand.wsu.edu/
http://communication.wsu.edu/
http://ucomm.wsu.edu/
http://education.wsu.edu/ (already listed)

These issues were experienced on the following devices - OS - Browser:
Motorola Droid Razr HD - Android 4.4.2 - Chrome
Motorola Moto X - Android 4.4.4 - Chrome
Samsung Galaxy S5 - Android 4.4.2 - Unknown
Samsung Galaxy Note 3 - Android 4.4.4 - Unknown

The navigation on some of these sites is large enough such that items are off screen.

**Comment by laffky** [comment]
Here is another phone experiencing the same issue.

Samsung S3 - Android 4.4.2 - Firefox 36.0.1

I forgot to ask this in the previous message, has any progress been made on this since the bug was opened?

**Comment by jeremyBass** [comment]
@laffky thank you for adding to the list.  

Some side notes, I took a look at your site and see that there are rules that are interfering with the spine, 
http://connections.wsu.edu/css/spine_adjustment.css , e.g. @~L31 the logo is being sized to a very small size.

I also notice that you are loading the spine from a local copy, 
`<link href="css/spine.min.css" rel="stylesheet" type="text/css">` and `<script src="scripts/spine.min.js"></script>` which we don't necessarily recommend.  We have put out many fixes, and if depending on what version you have, it may not include the fixes we currently have.  We suggest using `<link href="https://repo.wsu.edu/spine/1/spine.min.css" rel="stylesheet" type="text/css">` and `<script src="https://repo.wsu.edu/spine/1/spine.min.js"></script>` not only for the automatic fixes, but the user will more then likely have the files already cached, and ready to go.  Also we are moving toward having the assets on repo.wsu.edu served as a CDN.

**Comment by laffky** [comment]
@jeremyBass Thanks for the information. I'll look into the adjustments made and see if that fixes the issue on that site. As for the local copy, we had some custom functionality on a different website that broke when an update was made, so we moved to using a local copy across our sites and testing things on development first.

Directly related to this bug, do you know a website where the navigation is working correctly on mobile devices that we could test? We definitely could have created the issue ourselves by making adjustments, but so far the navigation on all the sites we've found have been unable to scroll on our devices. If we do test one of these sites with mobile devices and find that they indeed don't work I can add that information in case it helps track down what you are working on :)

**Comment by jeremyBass** [comment]
@laffky I just tested brand.wsu.edu on an Android 4.4.2 in both the native app, and chrome and it worked as expected in the two phone's native browsers (which is very important), and in the chrome browser it fails as per this issue.  We know it's rooted with Android 4.4.x and a third party app like Chrome.  On the bright side it's  ~0.006% of all traffic under wsu.edu, but we are working on it and I hope to see it corrected in the next update.

I would ask if you could please clarify "The navigation on some of these sites is large enough such that items are off screen. "  is it that it's to tall, which is of this issue, or are you saying it was to wide? May be that could clear up if this is still related or something new.

Lastly, as far as the breakage from an update, maybe that was from trying it out while we were in our beta period?  We surely don't want to break anything, and all changes moving forward must be backwards compatible, or we will do a full point release so people will be able chose to upgrade at wlill.  We have a standing rule to not break any backwards compatibility and everything gets tested on the `develop` branch first so that we don't break live site, since about Q4 2014 IIRC.  

Side you can use  

`<link href="https://repo.wsu.edu/spine/1/spine.min.css" rel="stylesheet" type="text/css"> `

for live sites and for dev work and to see fixes that are coming up, 

` <link href="https://repo.wsu.edu/spine/develop/spine.min.css" rel="stylesheet" type="text/css"> `

This is also true of the `js` files.

**Comment by jeremyBass** [comment]
## UPDATE

So @natejacobson and I have talked about it, and want to make sure that we are providing a timely correction for fix this issue, and landing on applying the fix for iOS for Android as well.  This will match the two deceive types that have issue with the nav so they will have the same functionality.  We'll have this fix into the `develop` branch soon.

**Comment by jeremyBass** [comment]
After we apply the hot fix, we need to have some sort of plan to correct the functions.  I believe I have a solution that will work.  I have tested it on All issued devices and the concept works so far it seems.  I would be changing no structure at all *(although in the POC its not a 100%)* so we can apply the fix in the 1.x and holds backward compatibility.  

Basically, I ditched what was started with, and rewrote it ground up.  I changed the concept to something I feel is  going on to be a little more true to how browsers really function.  We are scrolling in a overflow-y regardless if it's on `<html>` or some random `<div>`, so I don't fighting the scroll bars I embrace them.  So that it still looks the same *(no visiable scrollbars)* we just hide the scrollbar when needed using css.  By no means is all of the math right *(the nav doesn't kick in on the way up right away because of the unfinished math)*, or is this a final POC but when you scroll down just a little and back up, you'll see it's just what we want.

http://codepen.io/jeremyBass/pen/RNEYYR

Will need more work, but I'm betting it'll be right on the money with full support from iOS, Android and all desktop browsers.

**Comment by jeremyfelt** [comment]
We need to fix this. I'm going to start digging this week with an android device.

> We landed on applying the fix for iOS on Android as well. This will match the two deceive types that have issues with the nav so they will have the same functionality. We'll have this fix into the develop branch soon. 

@jeremyBass do you still have this hot fix available?

**Comment by jeremyfelt** [comment]
FWIW, I've only heard the complaint about Android devices recently. Both iOS Chrome and Safari work fine.
