### ISSUE TITLE
Clarification on access link in Spine

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#280]
Our "Access" link goes to access.wsu.edu which redirects to oeo.wsu.edu.

On the WSU home page, we link "Accessibility" in the footer to http://accesscenter.wsu.edu/.

Should one of these be changed to match?

**Comment by natejacobson** [comment]
Excellent question. The access link in the Spine, among other things, is fulfilling a legal obligation, so we may want to learn from the AG what the most appropriate destination is. Perhaps Nicole could also speak into this with her experience. Whatever the case, it wouldn't be a change in the Spine, but rather a change to the redirection of access.wsu.edu. Each of the bottom-most links are intended as aliases so that the markup never has to change.
